### ISSUE TITLE
Clock Behavior:

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Hsinha1109/Analog-Stopwatch.github.io#5]
The JavaScript file is not provided, so it's unclear how the clock operates. Make sure that the clock hands move and update the time correctly when the "Start" button is clicked. Similarly, the "Stop" and "Reset" buttons should work as expected.

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109 Assign this issue to me under Hacktoberfest

**Comment by Hsinha1109** [comment]
index.js is causing merge conflicts

**Comment by Kapileswar-Moharana** [comment]
> index.js is causing merge conflicts

Ok Then I will Try to resolve them

**Comment by Kapileswar-Moharana** [comment]
> index.js is causing merge conflicts

@Hsinha1109 Please add "Hacktoberfest accepted" label to all of the PR accepted or raised by me, otherwise it will not be counted

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109 Check #11  App Issues Close KR rehe ho PR merge nahi kr rehe, Upar see har PR ke section main jakee message karnaa padd raha kii "Hacktoberfest Accepted " ka Label add karoo , Kya bhai main issues solve karuu yaa yahii sabb karuuu.... , Jara Apkaa kamm complte karoo "Label" Ad krkee PR ke pagee pee and Issue creation ki page pe..."PLEASE" Taki main santi see appka issue kee upar  kam karuuu....

![Screenshot 2023-10-24 202850](https://github.com/Hsinha1109/Analog-Stopwatch.github.io/assets/129049677/fe45bd3f-ec68-4212-b63d-09f2c9fae401)
