### ISSUE TITLE
Real-Time Clock: .

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Hsinha1109/Analog-Stopwatch.github.io#6]
Instead of setting the clock to a fixed time (00:00:00), make it display the current time when the page loads

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109  Assign This issue to me under Hacktoberfest

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109 As it is a Stop watch You mentioned here if you want to add real world time but keep touching on the start button then stop watch start. If You want these changes then Assign This Issue to me Under Hacktoberfest

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109 Sir suniye app agar #11 ko merge krdete achha hota because of Real time clock pe main Hourhand, Minute hand, and Second-hand ko functioning karpataa... as when you Reload the page It shows the Current Time, When you Click on Start Button It starts as Stopwatch n All , so I am Doing another issues app thhoda karlijiyee yee to akk sath code eit krkee PR raise kardunga sirr.. Thanks...

**Comment by Hsinha1109** [comment]
done

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109 Check It Sir Last one Just Check And Merge it ?

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109 #16 Check this PR Sir If No Issues Then Merge It Sir, Minor Changes has done so need to merge it, sir? Otherwise, some functions will not work properly. Sir  @Hsinha1109 Check The PR and Merge Sir #16
