### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Hsinha1109/Analog-Stopwatch.github.io#9]
Added Dark Mode To The Screen

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109 Assign This Issue To me Under Hacktoberfest

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109 Is there any issue with these issues or after finishing previous all , then after only have to assigned ?

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109 Assign This Issue to me under Hacktoberfest

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109 Ye issues karuu ya nahii reason to bataadoo sirr takii mainn Closee krddoo iskoo...yaa bakii 2 krnee kee baddd Assigned krogee... Then .. Ok App jara kamm krddoo labels ad krkee merge krdoo...

**Comment by Hsinha1109** [comment]
issues band krdo @Kapileswar-Moharana ek kam krlo tum ki sirf  ek fork krke  ek CONTRIBUTORS.MD  nam se fille bna do aur main usse merge kr dunga . hacktober me merge aur pull request hi count honi h so wo krlo

**Comment by Kapileswar-Moharana** [comment]
@Hsinha1109 ,..May be sir but appka repo usiko throgh milaa hai naa .. so tag Label to bantaa haii naa...   Well Sir M Closing the issues, now only I'm completing the issues you assigned... an you please merge or check if there any issues then tell me i will fix it ok.. just merge the issues on which i have worked ..
